default: midterm

a1: latex/a1.tex
	cd latex && xelatex a1.tex && mv a1.pdf ..

a2: latex/a2.tex
	cd latex && xelatex a2.tex && mv a2.pdf ..

midterm: latex/midterm.tex
	cd latex && xelatex midterm.tex && mv midterm.pdf ..
