default: a4

a1: latex/a1.tex
	cd latex && xelatex a1.tex && mv a1.pdf ..

a2: latex/a2.tex
	cd latex && xelatex a2.tex && mv a2.pdf ..

a3: latex/a3.tex
	cd latex && xelatex a3.tex && mv a3.pdf ..

midterm: latex/midterm.tex
	cd latex && xelatex midterm.tex && mv midterm.pdf ..

a4: latex/a4.tex
	cd latex && xelatex a4.tex && mv a4.pdf ..
