default: a4

a1: latex/a1.tex
	cd latex && xelatex a1.tex && mv a1.pdf ..

a2: latex/a1.tex
	cd latex && xelatex a2.tex && mv a2.pdf ..

a3: latex/a3.tex
	cd latex && xelatex a3.tex && mv a3.pdf ..

a4: latex/a4.tex
	cd latex && xelatex a4.tex && mv a4.pdf ..

a5: latex/a5.tex
	cd latex && xelatex a5.tex && mv a5.pdf ..

a6: latex/a6.tex
	cd latex && xelatex a6.tex && mv a6.pdf ..

a7: latex/a7.tex
	cd latex && xelatex a7.tex && mv a7.pdf ..

a8: latex/a8.tex
	cd latex && xelatex a8.tex && mv a8.pdf ..

a9: latex/a9.tex
	cd latex && xelatex a9.tex && mv a9.pdf ..
