default: a3

all: a2

a1: latex/a1.tex
	cd latex && xelatex a1.tex && mv a1.pdf ..

a2: latex/a2.tex
	cd latex && xelatex a2.tex && mv a2.pdf ..

a3: latex/a3.tex
	cd latex && xelatex a3.tex && mv a3.pdf ..
