default: HW1

HW1: latex/HW1.tex
	cd latex && xelatex HW1.tex && mv HW1.pdf ..

HW2: latex/HW1.tex
	cd latex && xelatex HW2.tex && mv HW2.pdf ..

HW3: latex/HW3.tex
	cd latex && xelatex HW3.tex && mv HW3.pdf ..

HW4: latex/HW4.tex
	cd latex && xelatex HW4.tex && mv HW4.pdf ..

HW5: latex/HW5.tex
	cd latex && xelatex HW5.tex && mv HW5.pdf ..

HW6: latex/HW6.tex
	cd latex && xelatex HW6.tex && mv HW6.pdf ..

HW7: latex/HW7.tex
	cd latex && xelatex HW7.tex && mv HW7.pdf ..

HW8: latex/HW8.tex
	cd latex && xelatex HW8.tex && mv HW8.pdf ..

HW9: latex/HW9.tex
	cd latex && xelatex HW9.tex && mv HW9.pdf ..

clean:
	rm -f *.pdf
	rm -f *~
	rm -f latex/*.log
	rm -f latex/*.aux
	rm -f latex/*.out
